---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://ifchange.ruhoh.com

posts:
  permalink: /:year/:month/:filename
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
