title : ÒÝ³ÈF2E
tagline: Blog Tagline
author :
  name : ifchange
  email : netman8410@gmail.com
  github : ifchange
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
